# Stuff in my ~
export PATH="${HOME}/bin:${PATH}"

[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh

if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi


test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
