#!/bin/bash
#
# (1) copy to: ~/bin/ssh-host-color
# (2) set:     alias ssh=~/bin/ssh-host-color
#
# Inspired from http://talkfast.org/2011/01/10/ssh-host-color
# Fork from https://gist.github.com/773849
#

mode=profile

set_term_bgcolor(){
  mode=term_bgcolor
  local R=$1
  local G=$2
  local B=$3
  /usr/bin/osascript <<EOF
tell application "iTerm"
  tell the current terminal
    tell the current session
      set background color to {$(($R*65535/255)), $(($G*65535/255)), $(($B*65535/255))}
    end tell
  end tell
end tell
EOF
}

reset_term_bgcolor() {
    set_term_bgcolor 20 20 20
}


 # Escape code found here: https://groups.google.com/forum/#!topic/iterm2-discuss/bLz7kpMjb28
set_term_profile() {
    mode=term_profile
    local profile=$1
    echo -e "\033]50;SetProfile=$profile\a"
}

reset_term_profile() {
    echo -e "\033]50;SetProfile=Default\a"
}


if [[ "$@" =~ firestorm ]]; then
  set_term_bgcolor 40 0 0
elif [[ "$@" =~ fireblade ]]; then
    set_term_bgcolor 40 20 0
elif [[ "$@" =~ mini ]]; then
  set_term_profile "SSH Mini"
fi

trap "reset_term_profile" EXIT

ssh $@
